name: CI Prod

on:
  push:
    branches: [ "master" ]

jobs:
  build_image:
    name: Build image -> Update manifest
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push push push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: arseniskobelev/skippo-landing-page:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
        env:
          BUILD_TAG: ${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  update-manifest:
    runs-on: ubuntu-latest
    needs: [ 'build_image' ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ArseniSkobelev/skippo-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      - name: Change image tag
        run: |
          new_image="arseniskobelev/skippo-landing-page:${{ github.sha }}"
          deployment_file="landing-page-prod/deployment.yaml"
          old_image=$(grep -oP "(?<=image: ).+" $deployment_file)
          sed -i "s|$old_image|$new_image|g" $deployment_file
      - uses: stefanzweifel/git-auto-commit-action@v4
