name: CI Prod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_image_update_manifest:
    name: Build image -> Update manifest
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push push push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: arseniskobelev/skippo-landing-page:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
        env:
          BUILD_TAG: ${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Clone manifest repo
        uses: actions/checkout@v2
        with:
          repository: arseniskobelev/skippo-infra
      - name: Update manifest file
        run: |
          # Install yq
          sudo pip3 install yq

          # Update the manifest file with the new build tag
          yq eval ".spec.template.spec.containers[0].image |= sub(\":.*\", \":${BUILD_TAG}\")" deployment.yaml
      - name: Commit and push changes
        run: |
          git config user.name "Arseni Skobelev"
          git config user.email "arseni.skobelev0@gmail.com"
          git add .
          git commit -m "Update manifest with build tag"
          git push
