name: CI Prod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_image:
    name: Build image -> Update manifest
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push push push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: arseniskobelev/skippo-landing-page:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
        env:
          BUILD_TAG: ${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  update-manifest:
    runs-on: ubuntu-latest
    needs: [ 'build_image' ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ArseniSkobelev/skippo-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "arseni.skobelev0@gmail.com"
          git config --global user.name "arseniskobelev"
          sed -i "s/:.*$/:${BUILD_TAG}/" path/to/manifest.yaml
          git add -A
          git commit -m "Updated image for - ${{ github.sha }}"
          git push origin master
