name: CI Prod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_image_update_manifest:
    name: Build image -> Update manifest
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push push push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: arseniskobelev/skippo-landing-page:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
        env:
          BUILD_TAG: ${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Clone manifest repo
        uses: actions/checkout@v2
        with:
          repository: ArseniSkobelev/skippo-infra
      - name: Update manifest file
        run: sed -i "s/:.*$/:${BUILD_TAG}/" deployment.yaml
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: CI
          CI_COMMIT_AUTHOR: skippo. CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
