name: Build and push

on:
  push:
    branches: [ 'development' ]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push push push
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: /
            areyoubusy/skippo-landing-page:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/development' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  update-manifest:
    runs-on: ubuntu-latest
    needs: [ 'build-and-push-docker-image' ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ArseniSkobelev/skippo-landing-page
          ref: 'development'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: /
          git config --global user.email "arseniskobelev0@gmail.com"
          git config --global user.name "arseniskobelev"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/skippo-landing-page:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -m "Updated image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin development
